FROM node:14

RUN apt-get update && apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev

WORKDIR /app

ARG NODE_ENV
ARG REACT_APP_PUBLIC_URL
ARG REACT_APP_CONFIG_SERVICE_URL
ARG REACT_APP_GATEWAY_URL
ARG REACT_APP_ENV
ARG REACT_APP_GOOGLE_ANALYTICS
ARG REACT_APP_INFURA_TOKEN
ARG REACT_APP_IPFS_GATEWAY
ARG REACT_APP_SENTRY_DSN
ARG REACT_APP_SAFE_APPS_RPC_INFURA_TOKEN
# For production environments
ARG REACT_APP_INTERCOM_ID
ARG REACT_APP_PORTIS_ID
ARG REACT_APP_SQUARELINK_ID
ARG REACT_APP_FORTMATIC_KEY
ARG REACT_APP_COLLECTIBLES_SOURCE
ARG REACT_APP_ETHERSCAN_API_KEY
ARG REACT_APP_ETHGASSTATION_API_KEY

COPY package.json ./

COPY yarn.lock ./

COPY  src/logic/contracts/artifacts ./src/logic/contracts/artifacts

RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "start"]
