version: '3.2'

services:
  safe-react:
    build:
      context: ./
      args:
          - NODE_ENV=${NODE_ENV}
          - REACT_APP_CONFIG_SERVICE_URL=${REACT_APP_CONFIG_SERVICE_URL}
          - REACT_APP_GATEWAY_URL=${REACT_APP_GATEWAY_URL}
          - REACT_APP_ENV=${REACT_APP_ENV}
          - REACT_APP_GOOGLE_ANALYTICS=${REACT_APP_GOOGLE_ANALYTICS}
          - REACT_APP_INFURA_TOKEN=${REACT_APP_INFURA_TOKEN}
          - REACT_APP_IPFS_GATEWAY=${REACT_APP_IPFS_GATEWAY}
          - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
          - REACT_APP_SAFE_APPS_RPC_INFURA_TOKEN=${REACT_APP_SAFE_APPS_RPC_INFURA_TOKEN}
          # For production environments
          - REACT_APP_INTERCOM_ID=${REACT_APP_INTERCOM_ID}
          - REACT_APP_PORTIS_ID=${REACT_APP_PORTIS_ID}
          - REACT_APP_SQUARELINK_ID=${REACT_APP_SQUARELINK_ID}
          - REACT_APP_FORTMATIC_KEY=${REACT_APP_FORTMATIC_KEY}
          - REACT_APP_COLLECTIBLES_SOURCE=${REACT_APP_COLLECTIBLES_SOURCE}
          - REACT_APP_ETHERSCAN_API_KEY=${REACT_APP_ETHERSCAN_API_KEY}
          - REACT_APP_ETHGASSTATION_API_KEY=${REACT_APP_ETHGASSTATION_API_KEY}
    volumes:
      - /app/node_modules
      - /app/src/types/contracts
      - ./:/app
    ports:
      - 3000:3000
