// flow-typed signature: 1dcae8f2428dbf43f98138c8c527a4c8
// flow-typed version: <<STUB>>/@welldone-software/why-did-you-render_v3.3.9/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@welldone-software/why-did-you-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@welldone-software/why-did-you-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender.min' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/esm/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/esm/whyDidYouRender.min' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/cjs/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/cjs/whyDidYouRender.min' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/esm/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/esm/whyDidYouRender.min' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/umd/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/dist/umd/whyDidYouRender.min' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/calculateDeepEqualDiffs' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/consts' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/defaultNotifier' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/findObjectsDifferences' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/getDisplayName' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/getUpdateInfo' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/normalizeOptions' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/patches/patchClassComponent' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/patches/patchForwardRefComponent' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/patches/patchFunctionalOrStrComponent' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/patches/patchMemoComponent' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/shouldTrack' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/utils' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/src/whyDidYouRender' {
  declare module.exports: any;
}

// Filename aliases
declare module '@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender.min.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender.min'>;
}
declare module '@welldone-software/why-did-you-render/dist/esm/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/esm/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/dist/esm/whyDidYouRender.min.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/esm/whyDidYouRender.min'>;
}
declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/cjs/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/no-classes-transpile/cjs/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/cjs/whyDidYouRender.min.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/no-classes-transpile/cjs/whyDidYouRender.min'>;
}
declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/esm/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/no-classes-transpile/esm/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/esm/whyDidYouRender.min.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/no-classes-transpile/esm/whyDidYouRender.min'>;
}
declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min'>;
}
declare module '@welldone-software/why-did-you-render/dist/umd/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/umd/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/dist/umd/whyDidYouRender.min.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/umd/whyDidYouRender.min'>;
}
declare module '@welldone-software/why-did-you-render/src/calculateDeepEqualDiffs.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/calculateDeepEqualDiffs'>;
}
declare module '@welldone-software/why-did-you-render/src/consts.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/consts'>;
}
declare module '@welldone-software/why-did-you-render/src/defaultNotifier.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/defaultNotifier'>;
}
declare module '@welldone-software/why-did-you-render/src/findObjectsDifferences.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/findObjectsDifferences'>;
}
declare module '@welldone-software/why-did-you-render/src/getDisplayName.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/getDisplayName'>;
}
declare module '@welldone-software/why-did-you-render/src/getUpdateInfo.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/getUpdateInfo'>;
}
declare module '@welldone-software/why-did-you-render/src/index' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src'>;
}
declare module '@welldone-software/why-did-you-render/src/index.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src'>;
}
declare module '@welldone-software/why-did-you-render/src/normalizeOptions.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/normalizeOptions'>;
}
declare module '@welldone-software/why-did-you-render/src/patches/patchClassComponent.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/patches/patchClassComponent'>;
}
declare module '@welldone-software/why-did-you-render/src/patches/patchForwardRefComponent.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/patches/patchForwardRefComponent'>;
}
declare module '@welldone-software/why-did-you-render/src/patches/patchFunctionalOrStrComponent.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/patches/patchFunctionalOrStrComponent'>;
}
declare module '@welldone-software/why-did-you-render/src/patches/patchMemoComponent.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/patches/patchMemoComponent'>;
}
declare module '@welldone-software/why-did-you-render/src/shouldTrack.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/shouldTrack'>;
}
declare module '@welldone-software/why-did-you-render/src/utils.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/utils'>;
}
declare module '@welldone-software/why-did-you-render/src/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/src/whyDidYouRender'>;
}
