// flow-typed signature: 8bfc0eb0795000bed1976434e91400ae
// flow-typed version: <<STUB>>/async-sema_v3.1.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-sema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-sema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-sema/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-sema/lib/index' {
  declare module.exports: $Exports<'async-sema/lib'>;
}
declare module 'async-sema/lib/index.js' {
  declare module.exports: $Exports<'async-sema/lib'>;
}
