// flow-typed signature: 2470e4df3226bf5856293d15929c5d50
// flow-typed version: <<STUB>>/connected-react-router_v6.6.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connected-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connected-react-router/esm/actions' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/ConnectedRouter' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/middleware' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/reducer' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/selectors' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/structure/immutable/getIn' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/structure/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/structure/plain/getIn' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/structure/plain' {
  declare module.exports: any;
}

declare module 'connected-react-router/esm/structure/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/actions' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/ConnectedRouter' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/middleware' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/reducer' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/selectors' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/immutable/getIn' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/plain/getIn' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/plain' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/umd/ConnectedReactRouter' {
  declare module.exports: any;
}

declare module 'connected-react-router/umd/ConnectedReactRouter.min' {
  declare module.exports: any;
}

declare module 'connected-react-router/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connected-react-router/esm/actions.js' {
  declare module.exports: $Exports<'connected-react-router/esm/actions'>;
}
declare module 'connected-react-router/esm/ConnectedRouter.js' {
  declare module.exports: $Exports<'connected-react-router/esm/ConnectedRouter'>;
}
declare module 'connected-react-router/esm/immutable.js' {
  declare module.exports: $Exports<'connected-react-router/esm/immutable'>;
}
declare module 'connected-react-router/esm/index' {
  declare module.exports: $Exports<'connected-react-router/esm'>;
}
declare module 'connected-react-router/esm/index.js' {
  declare module.exports: $Exports<'connected-react-router/esm'>;
}
declare module 'connected-react-router/esm/middleware.js' {
  declare module.exports: $Exports<'connected-react-router/esm/middleware'>;
}
declare module 'connected-react-router/esm/reducer.js' {
  declare module.exports: $Exports<'connected-react-router/esm/reducer'>;
}
declare module 'connected-react-router/esm/seamless-immutable.js' {
  declare module.exports: $Exports<'connected-react-router/esm/seamless-immutable'>;
}
declare module 'connected-react-router/esm/selectors.js' {
  declare module.exports: $Exports<'connected-react-router/esm/selectors'>;
}
declare module 'connected-react-router/esm/structure/immutable/getIn.js' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/immutable/getIn'>;
}
declare module 'connected-react-router/esm/structure/immutable/index' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/immutable'>;
}
declare module 'connected-react-router/esm/structure/immutable/index.js' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/immutable'>;
}
declare module 'connected-react-router/esm/structure/plain/getIn.js' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/plain/getIn'>;
}
declare module 'connected-react-router/esm/structure/plain/index' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/plain'>;
}
declare module 'connected-react-router/esm/structure/plain/index.js' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/plain'>;
}
declare module 'connected-react-router/esm/structure/seamless-immutable/index' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/seamless-immutable'>;
}
declare module 'connected-react-router/esm/structure/seamless-immutable/index.js' {
  declare module.exports: $Exports<'connected-react-router/esm/structure/seamless-immutable'>;
}
declare module 'connected-react-router/immutable.js' {
  declare module.exports: $Exports<'connected-react-router/immutable'>;
}
declare module 'connected-react-router/lib/actions.js' {
  declare module.exports: $Exports<'connected-react-router/lib/actions'>;
}
declare module 'connected-react-router/lib/ConnectedRouter.js' {
  declare module.exports: $Exports<'connected-react-router/lib/ConnectedRouter'>;
}
declare module 'connected-react-router/lib/immutable.js' {
  declare module.exports: $Exports<'connected-react-router/lib/immutable'>;
}
declare module 'connected-react-router/lib/index' {
  declare module.exports: $Exports<'connected-react-router/lib'>;
}
declare module 'connected-react-router/lib/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib'>;
}
declare module 'connected-react-router/lib/middleware.js' {
  declare module.exports: $Exports<'connected-react-router/lib/middleware'>;
}
declare module 'connected-react-router/lib/reducer.js' {
  declare module.exports: $Exports<'connected-react-router/lib/reducer'>;
}
declare module 'connected-react-router/lib/seamless-immutable.js' {
  declare module.exports: $Exports<'connected-react-router/lib/seamless-immutable'>;
}
declare module 'connected-react-router/lib/selectors.js' {
  declare module.exports: $Exports<'connected-react-router/lib/selectors'>;
}
declare module 'connected-react-router/lib/structure/immutable/getIn.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/immutable/getIn'>;
}
declare module 'connected-react-router/lib/structure/immutable/index' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/immutable'>;
}
declare module 'connected-react-router/lib/structure/immutable/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/immutable'>;
}
declare module 'connected-react-router/lib/structure/plain/getIn.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/plain/getIn'>;
}
declare module 'connected-react-router/lib/structure/plain/index' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/plain'>;
}
declare module 'connected-react-router/lib/structure/plain/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/plain'>;
}
declare module 'connected-react-router/lib/structure/seamless-immutable/index' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/seamless-immutable'>;
}
declare module 'connected-react-router/lib/structure/seamless-immutable/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/seamless-immutable'>;
}
declare module 'connected-react-router/seamless-immutable.js' {
  declare module.exports: $Exports<'connected-react-router/seamless-immutable'>;
}
declare module 'connected-react-router/umd/ConnectedReactRouter.js' {
  declare module.exports: $Exports<'connected-react-router/umd/ConnectedReactRouter'>;
}
declare module 'connected-react-router/umd/ConnectedReactRouter.min.js' {
  declare module.exports: $Exports<'connected-react-router/umd/ConnectedReactRouter.min'>;
}
declare module 'connected-react-router/webpack.config.js' {
  declare module.exports: $Exports<'connected-react-router/webpack.config'>;
}
