// flow-typed signature: 679bf917ad510e03db498f47eca96544
// flow-typed version: <<STUB>>/currency-flags_v^2.1.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'currency-flags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'currency-flags' {
  declare module.exports: any;
}
