// flow-typed signature: e0b11cd98817d59fdc9ed07230d34dde
// flow-typed version: <<STUB>>/ethereum-ens_v0.7.8/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereum-ens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereum-ens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereum-ens/src/abi' {
  declare module.exports: any;
}

declare module 'ethereum-ens/src/utils' {
  declare module.exports: any;
}

declare module 'ethereum-ens/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereum-ens/index' {
  declare module.exports: $Exports<'ethereum-ens'>;
}
declare module 'ethereum-ens/index.js' {
  declare module.exports: $Exports<'ethereum-ens'>;
}
declare module 'ethereum-ens/src/abi.js' {
  declare module.exports: $Exports<'ethereum-ens/src/abi'>;
}
declare module 'ethereum-ens/src/utils.js' {
  declare module.exports: $Exports<'ethereum-ens/src/utils'>;
}
declare module 'ethereum-ens/test/test.js' {
  declare module.exports: $Exports<'ethereum-ens/test/test'>;
}
