// flow-typed signature: b763be656561225bc1e468340ec4af36
// flow-typed version: <<STUB>>/ethereumjs-abi_v0.6.8/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-abi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-abi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-abi/lib' {
  declare module.exports: any;
}

declare module 'ethereumjs-abi/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-abi/index' {
  declare module.exports: $Exports<'ethereumjs-abi'>;
}
declare module 'ethereumjs-abi/index.js' {
  declare module.exports: $Exports<'ethereumjs-abi'>;
}
declare module 'ethereumjs-abi/lib/index' {
  declare module.exports: $Exports<'ethereumjs-abi/lib'>;
}
declare module 'ethereumjs-abi/lib/index.js' {
  declare module.exports: $Exports<'ethereumjs-abi/lib'>;
}
declare module 'ethereumjs-abi/test/index' {
  declare module.exports: $Exports<'ethereumjs-abi/test'>;
}
declare module 'ethereumjs-abi/test/index.js' {
  declare module.exports: $Exports<'ethereumjs-abi/test'>;
}
