// flow-typed signature: 257f7edaf77fffda41b532e22c147355
// flow-typed version: <<STUB>>/fortmatic_v^1.0.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fortmatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fortmatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fortmatic/dist/fortmatic' {
  declare module.exports: any;
}

declare module 'fortmatic/lib/fortmatic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fortmatic/dist/fortmatic.js' {
  declare module.exports: $Exports<'fortmatic/dist/fortmatic'>;
}
declare module 'fortmatic/lib/fortmatic.js' {
  declare module.exports: $Exports<'fortmatic/lib/fortmatic'>;
}
