// flow-typed signature: 31fcec9a50e7373fa86d8050c505b6e4
// flow-typed version: <<STUB>>/immortal-db_v^1.0.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immortal-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immortal-db' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immortal-db/dist/immortal-db' {
  declare module.exports: any;
}

declare module 'immortal-db/dist/immortal-db.min' {
  declare module.exports: any;
}

declare module 'immortal-db/src/cookie-store' {
  declare module.exports: any;
}

declare module 'immortal-db/src' {
  declare module.exports: any;
}

declare module 'immortal-db/src/indexed-db' {
  declare module.exports: any;
}

declare module 'immortal-db/src/web-storage' {
  declare module.exports: any;
}

declare module 'immortal-db/testing/safari-cross-origin-iframe/iframe' {
  declare module.exports: any;
}

declare module 'immortal-db/testing/test' {
  declare module.exports: any;
}

declare module 'immortal-db/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immortal-db/dist/immortal-db.js' {
  declare module.exports: $Exports<'immortal-db/dist/immortal-db'>;
}
declare module 'immortal-db/dist/immortal-db.min.js' {
  declare module.exports: $Exports<'immortal-db/dist/immortal-db.min'>;
}
declare module 'immortal-db/src/cookie-store.js' {
  declare module.exports: $Exports<'immortal-db/src/cookie-store'>;
}
declare module 'immortal-db/src/index' {
  declare module.exports: $Exports<'immortal-db/src'>;
}
declare module 'immortal-db/src/index.js' {
  declare module.exports: $Exports<'immortal-db/src'>;
}
declare module 'immortal-db/src/indexed-db.js' {
  declare module.exports: $Exports<'immortal-db/src/indexed-db'>;
}
declare module 'immortal-db/src/web-storage.js' {
  declare module.exports: $Exports<'immortal-db/src/web-storage'>;
}
declare module 'immortal-db/testing/safari-cross-origin-iframe/iframe.js' {
  declare module.exports: $Exports<'immortal-db/testing/safari-cross-origin-iframe/iframe'>;
}
declare module 'immortal-db/testing/test.js' {
  declare module.exports: $Exports<'immortal-db/testing/test'>;
}
declare module 'immortal-db/webpack.config.js' {
  declare module.exports: $Exports<'immortal-db/webpack.config'>;
}
