// flow-typed signature: 34844f2d068c8f62d0db62a231ae83c5
// flow-typed version: <<STUB>>/jest-dom_v4.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-dom/extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-dom/extend-expect.js' {
  declare module.exports: $Exports<'jest-dom/extend-expect'>;
}
declare module 'jest-dom/index' {
  declare module.exports: $Exports<'jest-dom'>;
}
declare module 'jest-dom/index.js' {
  declare module.exports: $Exports<'jest-dom'>;
}
