// flow-typed signature: 1b8175b8922bedb25de8c048cfb20009
// flow-typed version: <<STUB>>/material-ui-search-bar_v^1.0.0-beta.13/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-search-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-search-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-search-bar/lib/components/SearchBar' {
  declare module.exports: any;
}

declare module 'material-ui-search-bar/lib/components/SearchBar/SearchBar' {
  declare module.exports: any;
}

declare module 'material-ui-search-bar/lib' {
  declare module.exports: any;
}

declare module 'material-ui-search-bar/lib/styleguide/Wrapper' {
  declare module.exports: any;
}

declare module 'material-ui-search-bar/styleguide.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-search-bar/lib/components/SearchBar/index' {
  declare module.exports: $Exports<'material-ui-search-bar/lib/components/SearchBar'>;
}
declare module 'material-ui-search-bar/lib/components/SearchBar/index.js' {
  declare module.exports: $Exports<'material-ui-search-bar/lib/components/SearchBar'>;
}
declare module 'material-ui-search-bar/lib/components/SearchBar/SearchBar.js' {
  declare module.exports: $Exports<'material-ui-search-bar/lib/components/SearchBar/SearchBar'>;
}
declare module 'material-ui-search-bar/lib/index' {
  declare module.exports: $Exports<'material-ui-search-bar/lib'>;
}
declare module 'material-ui-search-bar/lib/index.js' {
  declare module.exports: $Exports<'material-ui-search-bar/lib'>;
}
declare module 'material-ui-search-bar/lib/styleguide/Wrapper.js' {
  declare module.exports: $Exports<'material-ui-search-bar/lib/styleguide/Wrapper'>;
}
declare module 'material-ui-search-bar/styleguide.config.js' {
  declare module.exports: $Exports<'material-ui-search-bar/styleguide.config'>;
}
