// flow-typed signature: ca5b75b975c4c8e8995b9030836dc2d7
// flow-typed version: <<STUB>>/notistack_vhttps://github.com/gnosis/notistack.git#v0.9.4/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notistack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notistack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notistack/build' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarContainer' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarContext' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.styles' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.util' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'notistack/build/useSnackbar' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/constants' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/warning' {
  declare module.exports: any;
}

declare module 'notistack/build/withSnackbar' {
  declare module.exports: any;
}

declare module 'notistack/examples/mobx-example/App' {
  declare module.exports: any;
}

declare module 'notistack/examples/mobx-example' {
  declare module.exports: any;
}

declare module 'notistack/examples/mobx-example/Notifier' {
  declare module.exports: any;
}

declare module 'notistack/examples/mobx-example/store/store' {
  declare module.exports: any;
}

declare module 'notistack/examples/redux-example/App' {
  declare module.exports: any;
}

declare module 'notistack/examples/redux-example' {
  declare module.exports: any;
}

declare module 'notistack/examples/redux-example/Notifier' {
  declare module.exports: any;
}

declare module 'notistack/examples/redux-example/redux/actions' {
  declare module.exports: any;
}

declare module 'notistack/examples/redux-example/redux/reducers' {
  declare module.exports: any;
}

declare module 'notistack/examples/simple-example/App' {
  declare module.exports: any;
}

declare module 'notistack/examples/simple-example' {
  declare module.exports: any;
}

declare module 'notistack/examples/simple-example/MessageButtons' {
  declare module.exports: any;
}

declare module 'notistack/src' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarContainer' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarContext' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/SnackbarItem.styles' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarItem/SnackbarItem.util' {
  declare module.exports: any;
}

declare module 'notistack/src/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'notistack/src/useSnackbar' {
  declare module.exports: any;
}

declare module 'notistack/src/utils/constants' {
  declare module.exports: any;
}

declare module 'notistack/src/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'notistack/src/utils/warning' {
  declare module.exports: any;
}

declare module 'notistack/src/withSnackbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notistack/build/index' {
  declare module.exports: $Exports<'notistack/build'>;
}
declare module 'notistack/build/index.js' {
  declare module.exports: $Exports<'notistack/build'>;
}
declare module 'notistack/build/SnackbarContainer.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarContainer'>;
}
declare module 'notistack/build/SnackbarContext.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarContext'>;
}
declare module 'notistack/build/SnackbarItem/index' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem'>;
}
declare module 'notistack/build/SnackbarItem/index.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.styles.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.styles'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.util.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.util'>;
}
declare module 'notistack/build/SnackbarProvider.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarProvider'>;
}
declare module 'notistack/build/useSnackbar.js' {
  declare module.exports: $Exports<'notistack/build/useSnackbar'>;
}
declare module 'notistack/build/utils/constants.js' {
  declare module.exports: $Exports<'notistack/build/utils/constants'>;
}
declare module 'notistack/build/utils/getDisplayName.js' {
  declare module.exports: $Exports<'notistack/build/utils/getDisplayName'>;
}
declare module 'notistack/build/utils/warning.js' {
  declare module.exports: $Exports<'notistack/build/utils/warning'>;
}
declare module 'notistack/build/withSnackbar.js' {
  declare module.exports: $Exports<'notistack/build/withSnackbar'>;
}
declare module 'notistack/examples/mobx-example/App.js' {
  declare module.exports: $Exports<'notistack/examples/mobx-example/App'>;
}
declare module 'notistack/examples/mobx-example/index' {
  declare module.exports: $Exports<'notistack/examples/mobx-example'>;
}
declare module 'notistack/examples/mobx-example/index.js' {
  declare module.exports: $Exports<'notistack/examples/mobx-example'>;
}
declare module 'notistack/examples/mobx-example/Notifier.js' {
  declare module.exports: $Exports<'notistack/examples/mobx-example/Notifier'>;
}
declare module 'notistack/examples/mobx-example/store/store.js' {
  declare module.exports: $Exports<'notistack/examples/mobx-example/store/store'>;
}
declare module 'notistack/examples/redux-example/App.js' {
  declare module.exports: $Exports<'notistack/examples/redux-example/App'>;
}
declare module 'notistack/examples/redux-example/index' {
  declare module.exports: $Exports<'notistack/examples/redux-example'>;
}
declare module 'notistack/examples/redux-example/index.js' {
  declare module.exports: $Exports<'notistack/examples/redux-example'>;
}
declare module 'notistack/examples/redux-example/Notifier.js' {
  declare module.exports: $Exports<'notistack/examples/redux-example/Notifier'>;
}
declare module 'notistack/examples/redux-example/redux/actions.js' {
  declare module.exports: $Exports<'notistack/examples/redux-example/redux/actions'>;
}
declare module 'notistack/examples/redux-example/redux/reducers.js' {
  declare module.exports: $Exports<'notistack/examples/redux-example/redux/reducers'>;
}
declare module 'notistack/examples/simple-example/App.js' {
  declare module.exports: $Exports<'notistack/examples/simple-example/App'>;
}
declare module 'notistack/examples/simple-example/index' {
  declare module.exports: $Exports<'notistack/examples/simple-example'>;
}
declare module 'notistack/examples/simple-example/index.js' {
  declare module.exports: $Exports<'notistack/examples/simple-example'>;
}
declare module 'notistack/examples/simple-example/MessageButtons.js' {
  declare module.exports: $Exports<'notistack/examples/simple-example/MessageButtons'>;
}
declare module 'notistack/src/index' {
  declare module.exports: $Exports<'notistack/src'>;
}
declare module 'notistack/src/index.js' {
  declare module.exports: $Exports<'notistack/src'>;
}
declare module 'notistack/src/SnackbarContainer.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarContainer'>;
}
declare module 'notistack/src/SnackbarContext.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarContext'>;
}
declare module 'notistack/src/SnackbarItem/index' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem'>;
}
declare module 'notistack/src/SnackbarItem/index.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem'>;
}
declare module 'notistack/src/SnackbarItem/SnackbarItem.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/SnackbarItem'>;
}
declare module 'notistack/src/SnackbarItem/SnackbarItem.styles.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/SnackbarItem.styles'>;
}
declare module 'notistack/src/SnackbarItem/SnackbarItem.util.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarItem/SnackbarItem.util'>;
}
declare module 'notistack/src/SnackbarProvider.js' {
  declare module.exports: $Exports<'notistack/src/SnackbarProvider'>;
}
declare module 'notistack/src/useSnackbar.js' {
  declare module.exports: $Exports<'notistack/src/useSnackbar'>;
}
declare module 'notistack/src/utils/constants.js' {
  declare module.exports: $Exports<'notistack/src/utils/constants'>;
}
declare module 'notistack/src/utils/getDisplayName.js' {
  declare module.exports: $Exports<'notistack/src/utils/getDisplayName'>;
}
declare module 'notistack/src/utils/warning.js' {
  declare module.exports: $Exports<'notistack/src/utils/warning'>;
}
declare module 'notistack/src/withSnackbar.js' {
  declare module.exports: $Exports<'notistack/src/withSnackbar'>;
}
