// flow-typed signature: e215c06fb9ec51e72b3ed908312ee496
// flow-typed version: <<STUB>>/polish_v^0.2.3/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polish/polish' {
  declare module.exports: any;
}

declare module 'polish/polish.min' {
  declare module.exports: any;
}

declare module 'polish/polish.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polish/polish.js' {
  declare module.exports: $Exports<'polish/polish'>;
}
declare module 'polish/polish.min.js' {
  declare module.exports: $Exports<'polish/polish.min'>;
}
declare module 'polish/polish.spec.js' {
  declare module.exports: $Exports<'polish/polish.spec'>;
}
