// flow-typed signature: 19c5eeedd333e80fc8c36291e8a8102e
// flow-typed version: <<STUB>>/postcss-simple-vars_v^5.0.2/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-simple-vars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-simple-vars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-simple-vars/index' {
  declare module.exports: $Exports<'postcss-simple-vars'>;
}
declare module 'postcss-simple-vars/index.js' {
  declare module.exports: $Exports<'postcss-simple-vars'>;
}
