// flow-typed signature: 0cf1b74654d41b6fa5fcc79e717c613f
// flow-typed version: <<STUB>>/postcss-simple-vars_v^4.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-simple-vars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-simple-vars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-simple-vars/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-simple-vars/index' {
  declare module.exports: $Exports<'postcss-simple-vars'>;
}
declare module 'postcss-simple-vars/index.js' {
  declare module.exports: $Exports<'postcss-simple-vars'>;
}
declare module 'postcss-simple-vars/index.test.js' {
  declare module.exports: $Exports<'postcss-simple-vars/index.test'>;
}
