// flow-typed signature: ff136e8568ac477c05b6366f510c17f9
// flow-typed version: <<STUB>>/qrcode.react_v1.0.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode.react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode.react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrcode.react/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrcode.react/lib/index' {
  declare module.exports: $Exports<'qrcode.react/lib'>;
}
declare module 'qrcode.react/lib/index.js' {
  declare module.exports: $Exports<'qrcode.react/lib'>;
}
