// flow-typed signature: 0263e9e9a8b1e1b00f24616149d6cdec
// flow-typed version: <<STUB>>/qrcode.react_v1.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode.react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode.react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrcode.react/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrcode.react/lib/index' {
  declare module.exports: $Exports<'qrcode.react/lib'>;
}
declare module 'qrcode.react/lib/index.js' {
  declare module.exports: $Exports<'qrcode.react/lib'>;
}
