// flow-typed signature: 1e75e72b4f3234be07c5d1758d1c272e
// flow-typed version: <<STUB>>/react-qr-reader_v^2.2.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-qr-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-qr-reader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-qr-reader/examples/example' {
  declare module.exports: any;
}

declare module 'react-qr-reader/examples/legacy-mode' {
  declare module.exports: any;
}

declare module 'react-qr-reader/gulpfile' {
  declare module.exports: any;
}

declare module 'react-qr-reader/lib/createBlob' {
  declare module.exports: any;
}

declare module 'react-qr-reader/lib/errors' {
  declare module.exports: any;
}

declare module 'react-qr-reader/lib/getDeviceId' {
  declare module.exports: any;
}

declare module 'react-qr-reader/lib/havePropsChanged' {
  declare module.exports: any;
}

declare module 'react-qr-reader/lib' {
  declare module.exports: any;
}

declare module 'react-qr-reader/src/createBlob' {
  declare module.exports: any;
}

declare module 'react-qr-reader/src/errors' {
  declare module.exports: any;
}

declare module 'react-qr-reader/src/getDeviceId' {
  declare module.exports: any;
}

declare module 'react-qr-reader/src/havePropsChanged' {
  declare module.exports: any;
}

declare module 'react-qr-reader/src' {
  declare module.exports: any;
}

declare module 'react-qr-reader/src/worker' {
  declare module.exports: any;
}

declare module 'react-qr-reader/stories/index.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-qr-reader/examples/example.js' {
  declare module.exports: $Exports<'react-qr-reader/examples/example'>;
}
declare module 'react-qr-reader/examples/legacy-mode.js' {
  declare module.exports: $Exports<'react-qr-reader/examples/legacy-mode'>;
}
declare module 'react-qr-reader/gulpfile.js' {
  declare module.exports: $Exports<'react-qr-reader/gulpfile'>;
}
declare module 'react-qr-reader/lib/createBlob.js' {
  declare module.exports: $Exports<'react-qr-reader/lib/createBlob'>;
}
declare module 'react-qr-reader/lib/errors.js' {
  declare module.exports: $Exports<'react-qr-reader/lib/errors'>;
}
declare module 'react-qr-reader/lib/getDeviceId.js' {
  declare module.exports: $Exports<'react-qr-reader/lib/getDeviceId'>;
}
declare module 'react-qr-reader/lib/havePropsChanged.js' {
  declare module.exports: $Exports<'react-qr-reader/lib/havePropsChanged'>;
}
declare module 'react-qr-reader/lib/index' {
  declare module.exports: $Exports<'react-qr-reader/lib'>;
}
declare module 'react-qr-reader/lib/index.js' {
  declare module.exports: $Exports<'react-qr-reader/lib'>;
}
declare module 'react-qr-reader/src/createBlob.js' {
  declare module.exports: $Exports<'react-qr-reader/src/createBlob'>;
}
declare module 'react-qr-reader/src/errors.js' {
  declare module.exports: $Exports<'react-qr-reader/src/errors'>;
}
declare module 'react-qr-reader/src/getDeviceId.js' {
  declare module.exports: $Exports<'react-qr-reader/src/getDeviceId'>;
}
declare module 'react-qr-reader/src/havePropsChanged.js' {
  declare module.exports: $Exports<'react-qr-reader/src/havePropsChanged'>;
}
declare module 'react-qr-reader/src/index' {
  declare module.exports: $Exports<'react-qr-reader/src'>;
}
declare module 'react-qr-reader/src/index.js' {
  declare module.exports: $Exports<'react-qr-reader/src'>;
}
declare module 'react-qr-reader/src/worker.js' {
  declare module.exports: $Exports<'react-qr-reader/src/worker'>;
}
declare module 'react-qr-reader/stories/index.stories.js' {
  declare module.exports: $Exports<'react-qr-reader/stories/index.stories'>;
}
