// flow-typed signature: 0f1ea5f108966dfad63504b31d6a9a18
// flow-typed version: <<STUB>>/react-intercom_v^1.0.15/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intercom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intercom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intercom/lib' {
  declare module.exports: any;
}

declare module 'react-intercom/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intercom/lib/index' {
  declare module.exports: $Exports<'react-intercom/lib'>;
}
declare module 'react-intercom/lib/index.js' {
  declare module.exports: $Exports<'react-intercom/lib'>;
}
declare module 'react-intercom/src/index' {
  declare module.exports: $Exports<'react-intercom/src'>;
}
declare module 'react-intercom/src/index.js' {
  declare module.exports: $Exports<'react-intercom/src'>;
}
