// flow-typed signature: 0c544369c683430feae80f945f0237d8
// flow-typed version: <<STUB>>/run-with-testrpc_v0.3.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'run-with-testrpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'run-with-testrpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'run-with-testrpc/bin/run-with-testrpc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'run-with-testrpc/bin/run-with-testrpc.js' {
  declare module.exports: $Exports<'run-with-testrpc/bin/run-with-testrpc'>;
}
