// flow-typed signature: 7488a0e2e38d5417e371f62c9655f90d
// flow-typed version: <<STUB>>/squarelink_v^1.1.3/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'squarelink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'squarelink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'squarelink/dist/config' {
  declare module.exports: any;
}

declare module 'squarelink/dist/error' {
  declare module.exports: any;
}

declare module 'squarelink/dist/iframe' {
  declare module.exports: any;
}

declare module 'squarelink/dist' {
  declare module.exports: any;
}

declare module 'squarelink/dist/networks' {
  declare module.exports: any;
}

declare module 'squarelink/dist/popup' {
  declare module.exports: any;
}

declare module 'squarelink/dist/styles' {
  declare module.exports: any;
}

declare module 'squarelink/dist/util' {
  declare module.exports: any;
}

declare module 'squarelink/dist/walletMethods' {
  declare module.exports: any;
}

declare module 'squarelink/lib/squarelink.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'squarelink/dist/config.js' {
  declare module.exports: $Exports<'squarelink/dist/config'>;
}
declare module 'squarelink/dist/error.js' {
  declare module.exports: $Exports<'squarelink/dist/error'>;
}
declare module 'squarelink/dist/iframe.js' {
  declare module.exports: $Exports<'squarelink/dist/iframe'>;
}
declare module 'squarelink/dist/index' {
  declare module.exports: $Exports<'squarelink/dist'>;
}
declare module 'squarelink/dist/index.js' {
  declare module.exports: $Exports<'squarelink/dist'>;
}
declare module 'squarelink/dist/networks.js' {
  declare module.exports: $Exports<'squarelink/dist/networks'>;
}
declare module 'squarelink/dist/popup.js' {
  declare module.exports: $Exports<'squarelink/dist/popup'>;
}
declare module 'squarelink/dist/styles.js' {
  declare module.exports: $Exports<'squarelink/dist/styles'>;
}
declare module 'squarelink/dist/util.js' {
  declare module.exports: $Exports<'squarelink/dist/util'>;
}
declare module 'squarelink/dist/walletMethods.js' {
  declare module.exports: $Exports<'squarelink/dist/walletMethods'>;
}
declare module 'squarelink/lib/squarelink.min.js' {
  declare module.exports: $Exports<'squarelink/lib/squarelink.min'>;
}
