// flow-typed signature: 48ec61af419d1ece506839678031f356
// flow-typed version: <<STUB>>/storybook-host_v5.1.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-host'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-host' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-host/lib/common/alignment' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/color' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/css' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/glamor' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/test/css-flex.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/test/css-image.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/test/css-positioning.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/test/css-spacing.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/test/css.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css/types' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/libs' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/util' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/AlignmentContainer/AlignmentContainer' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/AlignmentContainer/ComponentHost.stories' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/AlignmentContainer' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/ComponentHost/ComponentHost' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/ComponentHost/ComponentHost.stories' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/ComponentHost' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/CropMarks/CropMark' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/CropMarks/CropMarks' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/CropMarks' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/decorators/host' {
  declare module.exports: any;
}

declare module 'storybook-host/lib' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/index.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/test/Foo' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-host/lib/common/alignment.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/alignment'>;
}
declare module 'storybook-host/lib/common/color.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/color'>;
}
declare module 'storybook-host/lib/common/css/css.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/css'>;
}
declare module 'storybook-host/lib/common/css/glamor.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/glamor'>;
}
declare module 'storybook-host/lib/common/css/index' {
  declare module.exports: $Exports<'storybook-host/lib/common/css'>;
}
declare module 'storybook-host/lib/common/css/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css'>;
}
declare module 'storybook-host/lib/common/css/test/css-flex.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/test/css-flex.test'>;
}
declare module 'storybook-host/lib/common/css/test/css-image.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/test/css-image.test'>;
}
declare module 'storybook-host/lib/common/css/test/css-positioning.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/test/css-positioning.test'>;
}
declare module 'storybook-host/lib/common/css/test/css-spacing.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/test/css-spacing.test'>;
}
declare module 'storybook-host/lib/common/css/test/css.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/test/css.test'>;
}
declare module 'storybook-host/lib/common/css/types.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css/types'>;
}
declare module 'storybook-host/lib/common/index' {
  declare module.exports: $Exports<'storybook-host/lib/common'>;
}
declare module 'storybook-host/lib/common/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/common'>;
}
declare module 'storybook-host/lib/common/libs.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/libs'>;
}
declare module 'storybook-host/lib/common/util.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/util'>;
}
declare module 'storybook-host/lib/components/AlignmentContainer/AlignmentContainer.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/AlignmentContainer/AlignmentContainer'>;
}
declare module 'storybook-host/lib/components/AlignmentContainer/ComponentHost.stories.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/AlignmentContainer/ComponentHost.stories'>;
}
declare module 'storybook-host/lib/components/AlignmentContainer/index' {
  declare module.exports: $Exports<'storybook-host/lib/components/AlignmentContainer'>;
}
declare module 'storybook-host/lib/components/AlignmentContainer/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/AlignmentContainer'>;
}
declare module 'storybook-host/lib/components/ComponentHost/ComponentHost.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/ComponentHost/ComponentHost'>;
}
declare module 'storybook-host/lib/components/ComponentHost/ComponentHost.stories.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/ComponentHost/ComponentHost.stories'>;
}
declare module 'storybook-host/lib/components/ComponentHost/index' {
  declare module.exports: $Exports<'storybook-host/lib/components/ComponentHost'>;
}
declare module 'storybook-host/lib/components/ComponentHost/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/ComponentHost'>;
}
declare module 'storybook-host/lib/components/CropMarks/CropMark.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/CropMarks/CropMark'>;
}
declare module 'storybook-host/lib/components/CropMarks/CropMarks.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/CropMarks/CropMarks'>;
}
declare module 'storybook-host/lib/components/CropMarks/index' {
  declare module.exports: $Exports<'storybook-host/lib/components/CropMarks'>;
}
declare module 'storybook-host/lib/components/CropMarks/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/CropMarks'>;
}
declare module 'storybook-host/lib/decorators/host.js' {
  declare module.exports: $Exports<'storybook-host/lib/decorators/host'>;
}
declare module 'storybook-host/lib/index' {
  declare module.exports: $Exports<'storybook-host/lib'>;
}
declare module 'storybook-host/lib/index.js' {
  declare module.exports: $Exports<'storybook-host/lib'>;
}
declare module 'storybook-host/lib/index.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/index.test'>;
}
declare module 'storybook-host/lib/test/Foo.js' {
  declare module.exports: $Exports<'storybook-host/lib/test/Foo'>;
}
declare module 'storybook-host/lib/test/index' {
  declare module.exports: $Exports<'storybook-host/lib/test'>;
}
declare module 'storybook-host/lib/test/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/test'>;
}
declare module 'storybook-host/lib/types.js' {
  declare module.exports: $Exports<'storybook-host/lib/types'>;
}
