// flow-typed signature: fee993f4b2e5a4e4a5d47c3068af36bd
// flow-typed version: <<STUB>>/truffle_v5.1.1/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle/build/analytics.bundled' {
  declare module.exports: any;
}

declare module 'truffle/build/chain.bundled' {
  declare module.exports: any;
}

declare module 'truffle/build/cli.bundled' {
  declare module.exports: any;
}

declare module 'truffle/build/library.bundled' {
  declare module.exports: any;
}

declare module 'truffle/build/templates/example' {
  declare module.exports: any;
}

declare module 'truffle/build/templates/migration' {
  declare module.exports: any;
}

declare module 'truffle/cli.webpack.config' {
  declare module.exports: any;
}

declare module 'truffle/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'truffle/scripts/prereleaseVersion' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commandrunner' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/build' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/deploy' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/ethpm' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/exec' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/help' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/init' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/install' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/migrate' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/networks' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/run' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commands/unbox' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/compile/compile' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/contract_names/test_imports' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/cyclic_dependencies/compiles' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/external_compilers/truffle-compile' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/genesis_time/genesis_time_invalid' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/genesis_time/genesis_time_undefined' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/genesis_time/genesis_time_valid' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/happy_path/happypath' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/library/api' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/memorylogger' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/describe-json' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/dryrun' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/errors' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/fabric-evm' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/init' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/migrate' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/production' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/quorum' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/reporter' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/resolver/resolver' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/sandbox' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/server' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/solidity_testing/solidityTests' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/typescript_testing/typescriptTests' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/build/projectWithBuildScript/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/build/projectWithObjectInBuildScript/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/build/projectWithoutBuildScript/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/contract_names/migrations/1_initial_migrations' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/contract_names/migrations/2_deploy_contract' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/contract_names/migrations/3_deploy_relative_import' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/contract_names/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/ethpm/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/exec/script' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/exec/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/external_compile/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/external_compile/migrations/2_deploy_contracts' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/external_compile/test/metacoin' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/external_compile/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/genesis_time/genesis_time_invalid/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/genesis_time/genesis_time_undefined/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/genesis_time/genesis_time_valid/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/inheritance/migrations/1_initial_migrations' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/inheritance/test/inheritance' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/inheritance/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/install/init/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/install/init/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/2_migrations_revert' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/3_migrations_ok' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/4_migrations_oog' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/5_migrations_reason' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/6_migrations_funds' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/7_batch_deployments' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/8_js_error_sync' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/migrations/9_js_error_async' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/error/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/fabric-evm/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/fabric-evm/migrations/2_migrations_sync' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/fabric-evm/migrations/3_migrations_async' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/fabric-evm/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/init/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/init/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/production/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/production/migrations/2_migrations_conf' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/production/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/quorum/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/quorum/migrations/2_migrations_sync' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/quorum/migrations/3_migrations_async' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/quorum/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/success/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/success/migrations/2_migrations_sync' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/success/migrations/3_migrations_async' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/migrations/success/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/monorepo/errorproject/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/monorepo/truffleproject/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/networks/metacoin/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/networks/metacoin/migrations/2_deploy_contracts' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/networks/metacoin/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithAbsolutePath/node_modules/truffle-mock' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithAbsolutePath/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithBadPluginFormat/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithMissingPluginConfig/node_modules/truffle-mock' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithMissingPluginConfig/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithMissingPluginModule/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithoutPlugin/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithPlugin/node_modules/truffle-mock' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithPlugin/truffle-config' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithWorkingPlugin/node_modules/truffle-mock' {
  declare module.exports: any;
}

declare module 'truffle/test/sources/run/mockProjectWithWorkingPlugin/truffle-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle/build/analytics.bundled.js' {
  declare module.exports: $Exports<'truffle/build/analytics.bundled'>;
}
declare module 'truffle/build/chain.bundled.js' {
  declare module.exports: $Exports<'truffle/build/chain.bundled'>;
}
declare module 'truffle/build/cli.bundled.js' {
  declare module.exports: $Exports<'truffle/build/cli.bundled'>;
}
declare module 'truffle/build/library.bundled.js' {
  declare module.exports: $Exports<'truffle/build/library.bundled'>;
}
declare module 'truffle/build/templates/example.js' {
  declare module.exports: $Exports<'truffle/build/templates/example'>;
}
declare module 'truffle/build/templates/migration.js' {
  declare module.exports: $Exports<'truffle/build/templates/migration'>;
}
declare module 'truffle/cli.webpack.config.js' {
  declare module.exports: $Exports<'truffle/cli.webpack.config'>;
}
declare module 'truffle/scripts/postinstall.js' {
  declare module.exports: $Exports<'truffle/scripts/postinstall'>;
}
declare module 'truffle/scripts/prereleaseVersion.js' {
  declare module.exports: $Exports<'truffle/scripts/prereleaseVersion'>;
}
declare module 'truffle/test/scenarios.js' {
  declare module.exports: $Exports<'truffle/test/scenarios'>;
}
declare module 'truffle/test/scenarios/commandrunner.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commandrunner'>;
}
declare module 'truffle/test/scenarios/commands/build.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/build'>;
}
declare module 'truffle/test/scenarios/commands/deploy.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/deploy'>;
}
declare module 'truffle/test/scenarios/commands/ethpm.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/ethpm'>;
}
declare module 'truffle/test/scenarios/commands/exec.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/exec'>;
}
declare module 'truffle/test/scenarios/commands/help.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/help'>;
}
declare module 'truffle/test/scenarios/commands/init.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/init'>;
}
declare module 'truffle/test/scenarios/commands/install.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/install'>;
}
declare module 'truffle/test/scenarios/commands/migrate.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/migrate'>;
}
declare module 'truffle/test/scenarios/commands/networks.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/networks'>;
}
declare module 'truffle/test/scenarios/commands/run.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/run'>;
}
declare module 'truffle/test/scenarios/commands/unbox.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commands/unbox'>;
}
declare module 'truffle/test/scenarios/compile/compile.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/compile/compile'>;
}
declare module 'truffle/test/scenarios/contract_names/test_imports.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/contract_names/test_imports'>;
}
declare module 'truffle/test/scenarios/cyclic_dependencies/compiles.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/cyclic_dependencies/compiles'>;
}
declare module 'truffle/test/scenarios/external_compilers/truffle-compile.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/external_compilers/truffle-compile'>;
}
declare module 'truffle/test/scenarios/genesis_time/genesis_time_invalid.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/genesis_time/genesis_time_invalid'>;
}
declare module 'truffle/test/scenarios/genesis_time/genesis_time_undefined.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/genesis_time/genesis_time_undefined'>;
}
declare module 'truffle/test/scenarios/genesis_time/genesis_time_valid.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/genesis_time/genesis_time_valid'>;
}
declare module 'truffle/test/scenarios/happy_path/happypath.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/happy_path/happypath'>;
}
declare module 'truffle/test/scenarios/library/api.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/library/api'>;
}
declare module 'truffle/test/scenarios/memorylogger.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/memorylogger'>;
}
declare module 'truffle/test/scenarios/migrations/describe-json.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/describe-json'>;
}
declare module 'truffle/test/scenarios/migrations/dryrun.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/dryrun'>;
}
declare module 'truffle/test/scenarios/migrations/errors.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/errors'>;
}
declare module 'truffle/test/scenarios/migrations/fabric-evm.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/fabric-evm'>;
}
declare module 'truffle/test/scenarios/migrations/init.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/init'>;
}
declare module 'truffle/test/scenarios/migrations/migrate.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/migrate'>;
}
declare module 'truffle/test/scenarios/migrations/production.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/production'>;
}
declare module 'truffle/test/scenarios/migrations/quorum.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/quorum'>;
}
declare module 'truffle/test/scenarios/reporter.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/reporter'>;
}
declare module 'truffle/test/scenarios/resolver/resolver.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/resolver/resolver'>;
}
declare module 'truffle/test/scenarios/sandbox.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/sandbox'>;
}
declare module 'truffle/test/scenarios/server.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/server'>;
}
declare module 'truffle/test/scenarios/solidity_testing/solidityTests.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/solidity_testing/solidityTests'>;
}
declare module 'truffle/test/scenarios/typescript_testing/typescriptTests.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/typescript_testing/typescriptTests'>;
}
declare module 'truffle/test/sources/build/projectWithBuildScript/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/build/projectWithBuildScript/truffle-config'>;
}
declare module 'truffle/test/sources/build/projectWithObjectInBuildScript/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/build/projectWithObjectInBuildScript/truffle-config'>;
}
declare module 'truffle/test/sources/build/projectWithoutBuildScript/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/build/projectWithoutBuildScript/truffle-config'>;
}
declare module 'truffle/test/sources/contract_names/migrations/1_initial_migrations.js' {
  declare module.exports: $Exports<'truffle/test/sources/contract_names/migrations/1_initial_migrations'>;
}
declare module 'truffle/test/sources/contract_names/migrations/2_deploy_contract.js' {
  declare module.exports: $Exports<'truffle/test/sources/contract_names/migrations/2_deploy_contract'>;
}
declare module 'truffle/test/sources/contract_names/migrations/3_deploy_relative_import.js' {
  declare module.exports: $Exports<'truffle/test/sources/contract_names/migrations/3_deploy_relative_import'>;
}
declare module 'truffle/test/sources/contract_names/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/contract_names/truffle-config'>;
}
declare module 'truffle/test/sources/ethpm/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/ethpm/truffle-config'>;
}
declare module 'truffle/test/sources/exec/script.js' {
  declare module.exports: $Exports<'truffle/test/sources/exec/script'>;
}
declare module 'truffle/test/sources/exec/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/exec/truffle-config'>;
}
declare module 'truffle/test/sources/external_compile/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/external_compile/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/external_compile/migrations/2_deploy_contracts.js' {
  declare module.exports: $Exports<'truffle/test/sources/external_compile/migrations/2_deploy_contracts'>;
}
declare module 'truffle/test/sources/external_compile/test/metacoin.js' {
  declare module.exports: $Exports<'truffle/test/sources/external_compile/test/metacoin'>;
}
declare module 'truffle/test/sources/external_compile/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/external_compile/truffle-config'>;
}
declare module 'truffle/test/sources/genesis_time/genesis_time_invalid/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/genesis_time/genesis_time_invalid/truffle-config'>;
}
declare module 'truffle/test/sources/genesis_time/genesis_time_undefined/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/genesis_time/genesis_time_undefined/truffle-config'>;
}
declare module 'truffle/test/sources/genesis_time/genesis_time_valid/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/genesis_time/genesis_time_valid/truffle-config'>;
}
declare module 'truffle/test/sources/inheritance/migrations/1_initial_migrations.js' {
  declare module.exports: $Exports<'truffle/test/sources/inheritance/migrations/1_initial_migrations'>;
}
declare module 'truffle/test/sources/inheritance/test/inheritance.js' {
  declare module.exports: $Exports<'truffle/test/sources/inheritance/test/inheritance'>;
}
declare module 'truffle/test/sources/inheritance/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/inheritance/truffle-config'>;
}
declare module 'truffle/test/sources/install/init/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/install/init/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/install/init/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/install/init/truffle-config'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/2_migrations_revert.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/2_migrations_revert'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/3_migrations_ok.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/3_migrations_ok'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/4_migrations_oog.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/4_migrations_oog'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/5_migrations_reason.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/5_migrations_reason'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/6_migrations_funds.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/6_migrations_funds'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/7_batch_deployments.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/7_batch_deployments'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/8_js_error_sync.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/8_js_error_sync'>;
}
declare module 'truffle/test/sources/migrations/error/migrations/9_js_error_async.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/migrations/9_js_error_async'>;
}
declare module 'truffle/test/sources/migrations/error/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/error/truffle-config'>;
}
declare module 'truffle/test/sources/migrations/fabric-evm/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/fabric-evm/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/migrations/fabric-evm/migrations/2_migrations_sync.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/fabric-evm/migrations/2_migrations_sync'>;
}
declare module 'truffle/test/sources/migrations/fabric-evm/migrations/3_migrations_async.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/fabric-evm/migrations/3_migrations_async'>;
}
declare module 'truffle/test/sources/migrations/fabric-evm/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/fabric-evm/truffle-config'>;
}
declare module 'truffle/test/sources/migrations/init/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/init/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/migrations/init/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/init/truffle-config'>;
}
declare module 'truffle/test/sources/migrations/production/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/production/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/migrations/production/migrations/2_migrations_conf.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/production/migrations/2_migrations_conf'>;
}
declare module 'truffle/test/sources/migrations/production/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/production/truffle-config'>;
}
declare module 'truffle/test/sources/migrations/quorum/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/quorum/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/migrations/quorum/migrations/2_migrations_sync.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/quorum/migrations/2_migrations_sync'>;
}
declare module 'truffle/test/sources/migrations/quorum/migrations/3_migrations_async.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/quorum/migrations/3_migrations_async'>;
}
declare module 'truffle/test/sources/migrations/quorum/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/quorum/truffle-config'>;
}
declare module 'truffle/test/sources/migrations/success/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/success/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/migrations/success/migrations/2_migrations_sync.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/success/migrations/2_migrations_sync'>;
}
declare module 'truffle/test/sources/migrations/success/migrations/3_migrations_async.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/success/migrations/3_migrations_async'>;
}
declare module 'truffle/test/sources/migrations/success/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/migrations/success/truffle-config'>;
}
declare module 'truffle/test/sources/monorepo/errorproject/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/monorepo/errorproject/truffle-config'>;
}
declare module 'truffle/test/sources/monorepo/truffleproject/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/monorepo/truffleproject/truffle-config'>;
}
declare module 'truffle/test/sources/networks/metacoin/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'truffle/test/sources/networks/metacoin/migrations/1_initial_migration'>;
}
declare module 'truffle/test/sources/networks/metacoin/migrations/2_deploy_contracts.js' {
  declare module.exports: $Exports<'truffle/test/sources/networks/metacoin/migrations/2_deploy_contracts'>;
}
declare module 'truffle/test/sources/networks/metacoin/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/networks/metacoin/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithAbsolutePath/node_modules/truffle-mock/index' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithAbsolutePath/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithAbsolutePath/node_modules/truffle-mock/index.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithAbsolutePath/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithAbsolutePath/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithAbsolutePath/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithBadPluginFormat/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithBadPluginFormat/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithMissingPluginConfig/node_modules/truffle-mock/index' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithMissingPluginConfig/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithMissingPluginConfig/node_modules/truffle-mock/index.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithMissingPluginConfig/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithMissingPluginConfig/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithMissingPluginConfig/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithMissingPluginModule/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithMissingPluginModule/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithoutPlugin/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithoutPlugin/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithPlugin/node_modules/truffle-mock/index' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithPlugin/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithPlugin/node_modules/truffle-mock/index.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithPlugin/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithPlugin/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithPlugin/truffle-config'>;
}
declare module 'truffle/test/sources/run/mockProjectWithWorkingPlugin/node_modules/truffle-mock/index' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithWorkingPlugin/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithWorkingPlugin/node_modules/truffle-mock/index.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithWorkingPlugin/node_modules/truffle-mock'>;
}
declare module 'truffle/test/sources/run/mockProjectWithWorkingPlugin/truffle-config.js' {
  declare module.exports: $Exports<'truffle/test/sources/run/mockProjectWithWorkingPlugin/truffle-config'>;
}
