// flow-typed signature: 4877782915fb90c08073243868f6b670
// flow-typed version: <<STUB>>/truffle-contract_v^1.1.8/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-contract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-contract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-contract/contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/dist/truffle-contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/dist/truffle-contract.min' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/lib/MetaCoin.sol' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/upgrade' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-contract/contract.js' {
  declare module.exports: $Exports<'truffle-contract/contract'>;
}
declare module 'truffle-contract/dist/truffle-contract.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract'>;
}
declare module 'truffle-contract/dist/truffle-contract.min.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract.min'>;
}
declare module 'truffle-contract/index' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/index.js' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/test/lib/MetaCoin.sol.js' {
  declare module.exports: $Exports<'truffle-contract/test/lib/MetaCoin.sol'>;
}
declare module 'truffle-contract/test/upgrade.js' {
  declare module.exports: $Exports<'truffle-contract/test/upgrade'>;
}
