// flow-typed signature: 2cbcee5e9c44377bc33b474b3b951a65
// flow-typed version: <<STUB>>/truffle-contract_v4.0.31/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-contract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-contract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-contract/dist/truffle-contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/dist/truffle-contract.min' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/bootstrap' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/constructorMethods' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/properties' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/execute' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/handlers' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/override' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/reason' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/reformat' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/statuserror' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/utils' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/abiV2' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/cloning' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/contract/constructorMethods' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/customoptions' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/deploy' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/deprecated_keys' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/errors' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/events' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/linking' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/methods' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/networkObject' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/networks' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/quorum' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/separation' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-contract/dist/truffle-contract.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract'>;
}
declare module 'truffle-contract/dist/truffle-contract.min.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract.min'>;
}
declare module 'truffle-contract/index' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/index.js' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/lib/contract.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract'>;
}
declare module 'truffle-contract/lib/contract/bootstrap.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/bootstrap'>;
}
declare module 'truffle-contract/lib/contract/constructorMethods.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/constructorMethods'>;
}
declare module 'truffle-contract/lib/contract/index' {
  declare module.exports: $Exports<'truffle-contract/lib/contract'>;
}
declare module 'truffle-contract/lib/contract/index.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract'>;
}
declare module 'truffle-contract/lib/contract/properties.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/properties'>;
}
declare module 'truffle-contract/lib/execute.js' {
  declare module.exports: $Exports<'truffle-contract/lib/execute'>;
}
declare module 'truffle-contract/lib/handlers.js' {
  declare module.exports: $Exports<'truffle-contract/lib/handlers'>;
}
declare module 'truffle-contract/lib/override.js' {
  declare module.exports: $Exports<'truffle-contract/lib/override'>;
}
declare module 'truffle-contract/lib/reason.js' {
  declare module.exports: $Exports<'truffle-contract/lib/reason'>;
}
declare module 'truffle-contract/lib/reformat.js' {
  declare module.exports: $Exports<'truffle-contract/lib/reformat'>;
}
declare module 'truffle-contract/lib/statuserror.js' {
  declare module.exports: $Exports<'truffle-contract/lib/statuserror'>;
}
declare module 'truffle-contract/lib/utils.js' {
  declare module.exports: $Exports<'truffle-contract/lib/utils'>;
}
declare module 'truffle-contract/test/abiV2.js' {
  declare module.exports: $Exports<'truffle-contract/test/abiV2'>;
}
declare module 'truffle-contract/test/cloning.js' {
  declare module.exports: $Exports<'truffle-contract/test/cloning'>;
}
declare module 'truffle-contract/test/contract/constructorMethods.js' {
  declare module.exports: $Exports<'truffle-contract/test/contract/constructorMethods'>;
}
declare module 'truffle-contract/test/customoptions.js' {
  declare module.exports: $Exports<'truffle-contract/test/customoptions'>;
}
declare module 'truffle-contract/test/deploy.js' {
  declare module.exports: $Exports<'truffle-contract/test/deploy'>;
}
declare module 'truffle-contract/test/deprecated_keys.js' {
  declare module.exports: $Exports<'truffle-contract/test/deprecated_keys'>;
}
declare module 'truffle-contract/test/errors.js' {
  declare module.exports: $Exports<'truffle-contract/test/errors'>;
}
declare module 'truffle-contract/test/events.js' {
  declare module.exports: $Exports<'truffle-contract/test/events'>;
}
declare module 'truffle-contract/test/linking.js' {
  declare module.exports: $Exports<'truffle-contract/test/linking'>;
}
declare module 'truffle-contract/test/methods.js' {
  declare module.exports: $Exports<'truffle-contract/test/methods'>;
}
declare module 'truffle-contract/test/networkObject.js' {
  declare module.exports: $Exports<'truffle-contract/test/networkObject'>;
}
declare module 'truffle-contract/test/networks.js' {
  declare module.exports: $Exports<'truffle-contract/test/networks'>;
}
declare module 'truffle-contract/test/quorum.js' {
  declare module.exports: $Exports<'truffle-contract/test/quorum'>;
}
declare module 'truffle-contract/test/separation.js' {
  declare module.exports: $Exports<'truffle-contract/test/separation'>;
}
declare module 'truffle-contract/test/util.js' {
  declare module.exports: $Exports<'truffle-contract/test/util'>;
}
