// flow-typed signature: 6fea208e73e0f7fa9d732718f7501edd
// flow-typed version: <<STUB>>/truffle-solidity-loader_v0.0.8/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-solidity-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-solidity-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-solidity-loader/lib/build_option_normalizer' {
  declare module.exports: any;
}

declare module 'truffle-solidity-loader/lib/logger_decorator' {
  declare module.exports: any;
}

declare module 'truffle-solidity-loader/lib/query_string_parser' {
  declare module.exports: any;
}

declare module 'truffle-solidity-loader/lib/scratch_dir' {
  declare module.exports: any;
}

declare module 'truffle-solidity-loader/lib/truffle_config_locator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-solidity-loader/index' {
  declare module.exports: $Exports<'truffle-solidity-loader'>;
}
declare module 'truffle-solidity-loader/index.js' {
  declare module.exports: $Exports<'truffle-solidity-loader'>;
}
declare module 'truffle-solidity-loader/lib/build_option_normalizer.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/build_option_normalizer'>;
}
declare module 'truffle-solidity-loader/lib/logger_decorator.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/logger_decorator'>;
}
declare module 'truffle-solidity-loader/lib/query_string_parser.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/query_string_parser'>;
}
declare module 'truffle-solidity-loader/lib/scratch_dir.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/scratch_dir'>;
}
declare module 'truffle-solidity-loader/lib/truffle_config_locator.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/truffle_config_locator'>;
}
