// flow-typed signature: a31d5257f9704184eca29fbf3a140e67
// flow-typed version: <<STUB>>/truffle-solidity-loader_v0.1.32/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-solidity-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-solidity-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-solidity-loader/lib/genBuildOptions' {
  declare module.exports: any;
}

declare module 'truffle-solidity-loader/lib/getTruffleConfig' {
  declare module.exports: any;
}

declare module 'truffle-solidity-loader/lib/logDecorator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-solidity-loader/index' {
  declare module.exports: $Exports<'truffle-solidity-loader'>;
}
declare module 'truffle-solidity-loader/index.js' {
  declare module.exports: $Exports<'truffle-solidity-loader'>;
}
declare module 'truffle-solidity-loader/lib/genBuildOptions.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/genBuildOptions'>;
}
declare module 'truffle-solidity-loader/lib/getTruffleConfig.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/getTruffleConfig'>;
}
declare module 'truffle-solidity-loader/lib/logDecorator.js' {
  declare module.exports: $Exports<'truffle-solidity-loader/lib/logDecorator'>;
}
