// flow-typed signature: 35a325d1f39c616d4cc834ae2b5e9f92
// flow-typed version: <<STUB>>/web3connect_v^1.0.0-beta.23/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3connect/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3connect/lib/index' {
  declare module.exports: $Exports<'web3connect/lib'>;
}
declare module 'web3connect/lib/index.js' {
  declare module.exports: $Exports<'web3connect/lib'>;
}
