// flow-typed signature: 8666795a60ea2a1f36479657ed47f791
// flow-typed version: <<STUB>>/web3_v1.2.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3/angular-patch' {
  declare module.exports: any;
}

declare module 'web3/dist/web3' {
  declare module.exports: any;
}

declare module 'web3/dist/web3.min' {
  declare module.exports: any;
}

declare module 'web3/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3/angular-patch.js' {
  declare module.exports: $Exports<'web3/angular-patch'>;
}
declare module 'web3/dist/web3.js' {
  declare module.exports: $Exports<'web3/dist/web3'>;
}
declare module 'web3/dist/web3.min.js' {
  declare module.exports: $Exports<'web3/dist/web3.min'>;
}
declare module 'web3/src/index' {
  declare module.exports: $Exports<'web3/src'>;
}
declare module 'web3/src/index.js' {
  declare module.exports: $Exports<'web3/src'>;
}
