// flow-typed signature: 7e463836ace64b04c97b6f81ac70b5ea
// flow-typed version: <<STUB>>/web3_v0.18.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3/dist/web3-light' {
  declare module.exports: any;
}

declare module 'web3/dist/web3-light.min' {
  declare module.exports: any;
}

declare module 'web3/dist/web3' {
  declare module.exports: any;
}

declare module 'web3/dist/web3.min' {
  declare module.exports: any;
}

declare module 'web3/example/node-app' {
  declare module.exports: any;
}

declare module 'web3/gulpfile' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/address' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/bool' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/bytes' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/coder' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/dynamicbytes' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/formatters' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/int' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/param' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/real' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/string' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/type' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/uint' {
  declare module.exports: any;
}

declare module 'web3/lib/solidity/ureal' {
  declare module.exports: any;
}

declare module 'web3/lib/utils/bloom' {
  declare module.exports: any;
}

declare module 'web3/lib/utils/browser-bn' {
  declare module.exports: any;
}

declare module 'web3/lib/utils/browser-xhr' {
  declare module.exports: any;
}

declare module 'web3/lib/utils/config' {
  declare module.exports: any;
}

declare module 'web3/lib/utils/sha3' {
  declare module.exports: any;
}

declare module 'web3/lib/utils/utils' {
  declare module.exports: any;
}

declare module 'web3/lib/web3' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/allevents' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/batch' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/contract' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/errors' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/event' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/extend' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/filter' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/formatters' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/function' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/httpprovider' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/iban' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/ipcprovider' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/jsonrpc' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/method' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/db' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/eth' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/net' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/personal' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/shh' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/swarm' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/methods/watches' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/namereg' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/property' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/requestmanager' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/settings' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/syncing' {
  declare module.exports: any;
}

declare module 'web3/lib/web3/transfer' {
  declare module.exports: any;
}

declare module 'web3/package-init' {
  declare module.exports: any;
}

declare module 'web3/package' {
  declare module.exports: any;
}

declare module 'web3/src/index_old' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3/dist/web3-light.js' {
  declare module.exports: $Exports<'web3/dist/web3-light'>;
}
declare module 'web3/dist/web3-light.min.js' {
  declare module.exports: $Exports<'web3/dist/web3-light.min'>;
}
declare module 'web3/dist/web3.js' {
  declare module.exports: $Exports<'web3/dist/web3'>;
}
declare module 'web3/dist/web3.min.js' {
  declare module.exports: $Exports<'web3/dist/web3.min'>;
}
declare module 'web3/example/node-app.js' {
  declare module.exports: $Exports<'web3/example/node-app'>;
}
declare module 'web3/gulpfile.js' {
  declare module.exports: $Exports<'web3/gulpfile'>;
}
declare module 'web3/index' {
  declare module.exports: $Exports<'web3'>;
}
declare module 'web3/index.js' {
  declare module.exports: $Exports<'web3'>;
}
declare module 'web3/lib/solidity/address.js' {
  declare module.exports: $Exports<'web3/lib/solidity/address'>;
}
declare module 'web3/lib/solidity/bool.js' {
  declare module.exports: $Exports<'web3/lib/solidity/bool'>;
}
declare module 'web3/lib/solidity/bytes.js' {
  declare module.exports: $Exports<'web3/lib/solidity/bytes'>;
}
declare module 'web3/lib/solidity/coder.js' {
  declare module.exports: $Exports<'web3/lib/solidity/coder'>;
}
declare module 'web3/lib/solidity/dynamicbytes.js' {
  declare module.exports: $Exports<'web3/lib/solidity/dynamicbytes'>;
}
declare module 'web3/lib/solidity/formatters.js' {
  declare module.exports: $Exports<'web3/lib/solidity/formatters'>;
}
declare module 'web3/lib/solidity/int.js' {
  declare module.exports: $Exports<'web3/lib/solidity/int'>;
}
declare module 'web3/lib/solidity/param.js' {
  declare module.exports: $Exports<'web3/lib/solidity/param'>;
}
declare module 'web3/lib/solidity/real.js' {
  declare module.exports: $Exports<'web3/lib/solidity/real'>;
}
declare module 'web3/lib/solidity/string.js' {
  declare module.exports: $Exports<'web3/lib/solidity/string'>;
}
declare module 'web3/lib/solidity/type.js' {
  declare module.exports: $Exports<'web3/lib/solidity/type'>;
}
declare module 'web3/lib/solidity/uint.js' {
  declare module.exports: $Exports<'web3/lib/solidity/uint'>;
}
declare module 'web3/lib/solidity/ureal.js' {
  declare module.exports: $Exports<'web3/lib/solidity/ureal'>;
}
declare module 'web3/lib/utils/bloom.js' {
  declare module.exports: $Exports<'web3/lib/utils/bloom'>;
}
declare module 'web3/lib/utils/browser-bn.js' {
  declare module.exports: $Exports<'web3/lib/utils/browser-bn'>;
}
declare module 'web3/lib/utils/browser-xhr.js' {
  declare module.exports: $Exports<'web3/lib/utils/browser-xhr'>;
}
declare module 'web3/lib/utils/config.js' {
  declare module.exports: $Exports<'web3/lib/utils/config'>;
}
declare module 'web3/lib/utils/sha3.js' {
  declare module.exports: $Exports<'web3/lib/utils/sha3'>;
}
declare module 'web3/lib/utils/utils.js' {
  declare module.exports: $Exports<'web3/lib/utils/utils'>;
}
declare module 'web3/lib/web3.js' {
  declare module.exports: $Exports<'web3/lib/web3'>;
}
declare module 'web3/lib/web3/allevents.js' {
  declare module.exports: $Exports<'web3/lib/web3/allevents'>;
}
declare module 'web3/lib/web3/batch.js' {
  declare module.exports: $Exports<'web3/lib/web3/batch'>;
}
declare module 'web3/lib/web3/contract.js' {
  declare module.exports: $Exports<'web3/lib/web3/contract'>;
}
declare module 'web3/lib/web3/errors.js' {
  declare module.exports: $Exports<'web3/lib/web3/errors'>;
}
declare module 'web3/lib/web3/event.js' {
  declare module.exports: $Exports<'web3/lib/web3/event'>;
}
declare module 'web3/lib/web3/extend.js' {
  declare module.exports: $Exports<'web3/lib/web3/extend'>;
}
declare module 'web3/lib/web3/filter.js' {
  declare module.exports: $Exports<'web3/lib/web3/filter'>;
}
declare module 'web3/lib/web3/formatters.js' {
  declare module.exports: $Exports<'web3/lib/web3/formatters'>;
}
declare module 'web3/lib/web3/function.js' {
  declare module.exports: $Exports<'web3/lib/web3/function'>;
}
declare module 'web3/lib/web3/httpprovider.js' {
  declare module.exports: $Exports<'web3/lib/web3/httpprovider'>;
}
declare module 'web3/lib/web3/iban.js' {
  declare module.exports: $Exports<'web3/lib/web3/iban'>;
}
declare module 'web3/lib/web3/ipcprovider.js' {
  declare module.exports: $Exports<'web3/lib/web3/ipcprovider'>;
}
declare module 'web3/lib/web3/jsonrpc.js' {
  declare module.exports: $Exports<'web3/lib/web3/jsonrpc'>;
}
declare module 'web3/lib/web3/method.js' {
  declare module.exports: $Exports<'web3/lib/web3/method'>;
}
declare module 'web3/lib/web3/methods/db.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/db'>;
}
declare module 'web3/lib/web3/methods/eth.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/eth'>;
}
declare module 'web3/lib/web3/methods/net.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/net'>;
}
declare module 'web3/lib/web3/methods/personal.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/personal'>;
}
declare module 'web3/lib/web3/methods/shh.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/shh'>;
}
declare module 'web3/lib/web3/methods/swarm.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/swarm'>;
}
declare module 'web3/lib/web3/methods/watches.js' {
  declare module.exports: $Exports<'web3/lib/web3/methods/watches'>;
}
declare module 'web3/lib/web3/namereg.js' {
  declare module.exports: $Exports<'web3/lib/web3/namereg'>;
}
declare module 'web3/lib/web3/property.js' {
  declare module.exports: $Exports<'web3/lib/web3/property'>;
}
declare module 'web3/lib/web3/requestmanager.js' {
  declare module.exports: $Exports<'web3/lib/web3/requestmanager'>;
}
declare module 'web3/lib/web3/settings.js' {
  declare module.exports: $Exports<'web3/lib/web3/settings'>;
}
declare module 'web3/lib/web3/syncing.js' {
  declare module.exports: $Exports<'web3/lib/web3/syncing'>;
}
declare module 'web3/lib/web3/transfer.js' {
  declare module.exports: $Exports<'web3/lib/web3/transfer'>;
}
declare module 'web3/package-init.js' {
  declare module.exports: $Exports<'web3/package-init'>;
}
declare module 'web3/package.js' {
  declare module.exports: $Exports<'web3/package'>;
}
declare module 'web3/src/index_old.js' {
  declare module.exports: $Exports<'web3/src/index_old'>;
}
