// flow-typed signature: dd33ab6d358e3ec9c9b9fbe0c77d7be5
// flow-typed version: <<STUB>>/@babel/plugin-transform-member-expression-literals_v^7.2.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-member-expression-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-member-expression-literals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-member-expression-literals/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-member-expression-literals/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-member-expression-literals/lib'>;
}
declare module '@babel/plugin-transform-member-expression-literals/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-member-expression-literals/lib'>;
}
