// flow-typed signature: 6c4433237be34e04c21f3a63f5498cde
// flow-typed version: <<STUB>>/@babel/plugin-syntax-import-meta_v7.7.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-import-meta'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-import-meta' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-import-meta/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-import-meta/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-import-meta/lib'>;
}
declare module '@babel/plugin-syntax-import-meta/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-import-meta/lib'>;
}
