// flow-typed signature: 1366774d9f3355070594bb88ce8bda8c
// flow-typed version: <<STUB>>/@babel/plugin-transform-property-literals_v7.7.4/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-property-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-property-literals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-property-literals/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-property-literals/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-property-literals/lib'>;
}
declare module '@babel/plugin-transform-property-literals/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-property-literals/lib'>;
}
