// flow-typed signature: 0d8aab922e89f42878bb98b5dbf44c6d
// flow-typed version: <<STUB>>/@babel/plugin-proposal-function-sent_v7.7.4/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-function-sent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-function-sent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-function-sent/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-function-sent/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-function-sent/lib'>;
}
declare module '@babel/plugin-proposal-function-sent/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-function-sent/lib'>;
}
