// flow-typed signature: 9a1a52278f9cd4bba64ec4247f833d1a
// flow-typed version: <<STUB>>/@babel/plugin-proposal-pipeline-operator_v7.5.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-pipeline-operator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-pipeline-operator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/smartVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/src/buildOptimizedSequenceExpression' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/src/fsharpVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/src' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/src/minimalVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/src/smartVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions-parenless/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/multiple-argument-use/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/multiple-argument-use/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/if/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/if/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-as-callee/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-as-callee/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart+arrow/await/exec' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/smartVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/smartVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/src/buildOptimizedSequenceExpression.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/src/buildOptimizedSequenceExpression'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/src/fsharpVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/src/fsharpVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/src/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/src'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/src/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/src'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/src/minimalVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/src/minimalVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/src/smartVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/src/smartVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions-parenless/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions-parenless/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/arrow-functions/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/await/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/basic/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/indirect-eval/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/multiple-argument-use/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/multiple-argument-use/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/multiple-argument-use/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/multiple-argument-use/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/fsharp/optimize-0-param-arrow/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions-parenless/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/arrow-functions/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/async-arrow/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/basic/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/chaining/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/currying/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/deoptimize-multi-param-arrow/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/destructure-arrow-param/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/evaluation/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/indirect-eval/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/multiple-argument-use/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/optimize-0-param-arrow/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/minimal/precedence/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/await/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/bare-function/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/basic/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-init/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for-update/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/for/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/if/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/if/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/if/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/if/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/indirect-eval/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/nested/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/object-literal/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-as-callee/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-as-callee/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-as-callee/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-as-callee/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/topic-inside-arrow-function/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/while/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/input'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart/yield/output'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/fixtures/smart+arrow/await/exec.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test/fixtures/smart+arrow/await/exec'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/test/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/test'>;
}
