// flow-typed signature: 09e0a6be4eeb2ba7360b27aebad3845e
// flow-typed version: <<STUB>>/@gnosis.pm/safe-contracts_v1.0.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@gnosis.pm/safe-contracts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@gnosis.pm/safe-contracts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@gnosis.pm/safe-contracts/test/createAndAddModules' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/dailyLimitModule' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEdition' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionCreation' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionCreation2' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionEthSignTypeData' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionManagers' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionNestedSafes' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionSignatureValidatorErrors' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/gnosisSafeTeamEdition' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/multiSend' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/safeMethodNaming' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/socialRecoveryModule' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/stateChannelModule' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/utils/execution' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/utils/general' {
  declare module.exports: any;
}

declare module '@gnosis.pm/safe-contracts/test/whitelistModule' {
  declare module.exports: any;
}

// Filename aliases
declare module '@gnosis.pm/safe-contracts/test/createAndAddModules.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/createAndAddModules'>;
}
declare module '@gnosis.pm/safe-contracts/test/dailyLimitModule.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/dailyLimitModule'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEdition.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEdition'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionCreation.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionCreation'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionCreation2.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionCreation2'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionEthSignTypeData.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionEthSignTypeData'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionManagers.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionManagers'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionNestedSafes.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionNestedSafes'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionSignatureValidatorErrors.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafePersonalEditionSignatureValidatorErrors'>;
}
declare module '@gnosis.pm/safe-contracts/test/gnosisSafeTeamEdition.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/gnosisSafeTeamEdition'>;
}
declare module '@gnosis.pm/safe-contracts/test/multiSend.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/multiSend'>;
}
declare module '@gnosis.pm/safe-contracts/test/safeMethodNaming.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/safeMethodNaming'>;
}
declare module '@gnosis.pm/safe-contracts/test/socialRecoveryModule.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/socialRecoveryModule'>;
}
declare module '@gnosis.pm/safe-contracts/test/stateChannelModule.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/stateChannelModule'>;
}
declare module '@gnosis.pm/safe-contracts/test/utils/execution.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/utils/execution'>;
}
declare module '@gnosis.pm/safe-contracts/test/utils/general.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/utils/general'>;
}
declare module '@gnosis.pm/safe-contracts/test/whitelistModule.js' {
  declare module.exports: $Exports<'@gnosis.pm/safe-contracts/test/whitelistModule'>;
}
