// flow-typed signature: b700798c2cbf29c43d53b822bc1a59c2
// flow-typed version: <<STUB>>/@gnosis.pm/util-contracts_v2.0.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@gnosis.pm/util-contracts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@gnosis.pm/util-contracts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@gnosis.pm/util-contracts/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/migrations/2_deploy_WETH' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/conf/network-restore' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/extract_network_info' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/inject_network_info' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4/2_deploy_math' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4/3_deploy_WETH' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5/2_deploy_math' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5/3_deploy_WETH' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/util/extractNetworks' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/util/HDWalletProvider' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/util/injectNetworks' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/util/injectNetworksDeps' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/util/networkUtils' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/src/util/truffleConfig' {
  declare module.exports: any;
}

declare module '@gnosis.pm/util-contracts/truffle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@gnosis.pm/util-contracts/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/migrations/1_initial_migration'>;
}
declare module '@gnosis.pm/util-contracts/migrations/2_deploy_WETH.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/migrations/2_deploy_WETH'>;
}
declare module '@gnosis.pm/util-contracts/src/conf/network-restore.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/conf/network-restore'>;
}
declare module '@gnosis.pm/util-contracts/src/extract_network_info.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/extract_network_info'>;
}
declare module '@gnosis.pm/util-contracts/src/inject_network_info.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/inject_network_info'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4/2_deploy_math.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-4/2_deploy_math'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4/3_deploy_WETH.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-4/3_deploy_WETH'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4/index' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-4'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-4/index.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-4'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5/2_deploy_math.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-5/2_deploy_math'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5/3_deploy_WETH.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-5/3_deploy_WETH'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5/index' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-5'>;
}
declare module '@gnosis.pm/util-contracts/src/migrations-truffle-5/index.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/migrations-truffle-5'>;
}
declare module '@gnosis.pm/util-contracts/src/util/extractNetworks.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/util/extractNetworks'>;
}
declare module '@gnosis.pm/util-contracts/src/util/HDWalletProvider.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/util/HDWalletProvider'>;
}
declare module '@gnosis.pm/util-contracts/src/util/injectNetworks.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/util/injectNetworks'>;
}
declare module '@gnosis.pm/util-contracts/src/util/injectNetworksDeps.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/util/injectNetworksDeps'>;
}
declare module '@gnosis.pm/util-contracts/src/util/networkUtils.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/util/networkUtils'>;
}
declare module '@gnosis.pm/util-contracts/src/util/truffleConfig.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/src/util/truffleConfig'>;
}
declare module '@gnosis.pm/util-contracts/truffle.js' {
  declare module.exports: $Exports<'@gnosis.pm/util-contracts/truffle'>;
}
