export const FIELD_LOAD_CUSTOM_SAFE_NAME = 'customSafeName'
export const FIELD_LOAD_SUGGESTED_SAFE_NAME = 'suggestedSafeName'
export const FIELD_LOAD_SAFE_ADDRESS = 'safeAddress'
export const FIELD_SAFE_OWNER_LIST = 'safeOwnerList'
export const FIELD_SAFE_THRESHOLD = 'safeThreshold'
