// flow-typed signature: 3ae28865f486ed67f1ca4e1bf7b08d07
// flow-typed version: <<STUB>>/@portis/web3_v^2.0.0-beta.45/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@portis/web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@portis/web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@portis/web3/es' {
  declare module.exports: any;
}

declare module '@portis/web3/es/interfaces' {
  declare module.exports: any;
}

declare module '@portis/web3/es/networks' {
  declare module.exports: any;
}

declare module '@portis/web3/es/styles' {
  declare module.exports: any;
}

declare module '@portis/web3/es/utils/getTxGas' {
  declare module.exports: any;
}

declare module '@portis/web3/es/utils/onWindowLoad' {
  declare module.exports: any;
}

declare module '@portis/web3/es/utils/query' {
  declare module.exports: any;
}

declare module '@portis/web3/es/utils/secureOrigin' {
  declare module.exports: any;
}

declare module '@portis/web3/lib' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/interfaces' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/networks' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/styles' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/utils/getTxGas' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/utils/onWindowLoad' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/utils/query' {
  declare module.exports: any;
}

declare module '@portis/web3/lib/utils/secureOrigin' {
  declare module.exports: any;
}

declare module '@portis/web3/umd' {
  declare module.exports: any;
}

declare module '@portis/web3/utils/integrity' {
  declare module.exports: any;
}

// Filename aliases
declare module '@portis/web3/es/index' {
  declare module.exports: $Exports<'@portis/web3/es'>;
}
declare module '@portis/web3/es/index.js' {
  declare module.exports: $Exports<'@portis/web3/es'>;
}
declare module '@portis/web3/es/interfaces.js' {
  declare module.exports: $Exports<'@portis/web3/es/interfaces'>;
}
declare module '@portis/web3/es/networks.js' {
  declare module.exports: $Exports<'@portis/web3/es/networks'>;
}
declare module '@portis/web3/es/styles.js' {
  declare module.exports: $Exports<'@portis/web3/es/styles'>;
}
declare module '@portis/web3/es/utils/getTxGas.js' {
  declare module.exports: $Exports<'@portis/web3/es/utils/getTxGas'>;
}
declare module '@portis/web3/es/utils/onWindowLoad.js' {
  declare module.exports: $Exports<'@portis/web3/es/utils/onWindowLoad'>;
}
declare module '@portis/web3/es/utils/query.js' {
  declare module.exports: $Exports<'@portis/web3/es/utils/query'>;
}
declare module '@portis/web3/es/utils/secureOrigin.js' {
  declare module.exports: $Exports<'@portis/web3/es/utils/secureOrigin'>;
}
declare module '@portis/web3/lib/index' {
  declare module.exports: $Exports<'@portis/web3/lib'>;
}
declare module '@portis/web3/lib/index.js' {
  declare module.exports: $Exports<'@portis/web3/lib'>;
}
declare module '@portis/web3/lib/interfaces.js' {
  declare module.exports: $Exports<'@portis/web3/lib/interfaces'>;
}
declare module '@portis/web3/lib/networks.js' {
  declare module.exports: $Exports<'@portis/web3/lib/networks'>;
}
declare module '@portis/web3/lib/styles.js' {
  declare module.exports: $Exports<'@portis/web3/lib/styles'>;
}
declare module '@portis/web3/lib/utils/getTxGas.js' {
  declare module.exports: $Exports<'@portis/web3/lib/utils/getTxGas'>;
}
declare module '@portis/web3/lib/utils/onWindowLoad.js' {
  declare module.exports: $Exports<'@portis/web3/lib/utils/onWindowLoad'>;
}
declare module '@portis/web3/lib/utils/query.js' {
  declare module.exports: $Exports<'@portis/web3/lib/utils/query'>;
}
declare module '@portis/web3/lib/utils/secureOrigin.js' {
  declare module.exports: $Exports<'@portis/web3/lib/utils/secureOrigin'>;
}
declare module '@portis/web3/umd/index' {
  declare module.exports: $Exports<'@portis/web3/umd'>;
}
declare module '@portis/web3/umd/index.js' {
  declare module.exports: $Exports<'@portis/web3/umd'>;
}
declare module '@portis/web3/utils/integrity.js' {
  declare module.exports: $Exports<'@portis/web3/utils/integrity'>;
}
