/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IChocoInitializable } from "../IChocoInitializable";

export class IChocoInitializable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChocoInitializable {
    return new Contract(address, _abi, signerOrProvider) as IChocoInitializable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
