import { makeStyles, Theme } from '@material-ui/core/styles'

const defaultButtonWidth = '140px'
export const useDropdownStyles = makeStyles<Theme, { buttonWidth?: string }>(({ palette }) => ({
  listItem: {
    maxWidth: ({ buttonWidth }) => buttonWidth || defaultButtonWidth,
    boxSizing: 'border-box',
  },
  listItemSearch: {
    maxWidth: ({ buttonWidth }) => buttonWidth || defaultButtonWidth,
    padding: '0',
    boxSizing: 'border-box',
  },
  localFlag: {
    backgroundPosition: '50% 50%',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'contain',
    height: '20px !important',
    width: '26px !important',
  },
  etherFlag: {
    backgroundPosition: '50% 50%',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'contain',
    width: '26px',
    height: '26px',
  },
  iconLeft: {
    marginRight: '10px',
  },
  iconRight: {
    marginLeft: '18px',
  },
  button: {
    backgroundColor: palette.grey4[palette.type],
    border: 'none',
    borderRadius: '3px',
    boxSizing: 'border-box',
    color: palette.secondaryLabel[palette.type],
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 'normal',
    height: '24px',
    lineHeight: '1.33',
    marginRight: '20px',
    minWidth: ({ buttonWidth }) => buttonWidth || defaultButtonWidth,
    outline: 'none',
    padding: '0',
    textAlign: 'left',
    '&:active': {
      opacity: '0.8',
    },
  },
  buttonInner: {
    boxSizing: 'border-box',
    display: 'block',
    height: '100%',
    lineHeight: '24px',
    padding: '0 22px 0 8px',
    position: 'relative',
    width: '100%',
    '&::after': {
      borderLeft: '5px solid transparent',
      borderRight: '5px solid transparent',
      borderTop: `5px solid ${palette.secondaryLabel[palette.type]}`,
      content: '""',
      height: '0',
      position: 'absolute',
      right: '8px',
      top: '9px',
      width: '0',
    },
  },
  openMenuButton: {
    '&::after': {
      borderBottom: `5px solid ${palette.secondaryLabel[palette.type]}`,
      borderLeft: '5px solid transparent',
      borderRight: '5px solid transparent',
      borderTop: 'none',
    },
  },
  dropdownItemsScrollWrapper: {
    maxHeight: '280px',
    overflow: 'auto',
  },
  search: {
    position: 'relative',
    borderRadius: '0',
    backgroundColor: palette.surface01dp[palette.type],
    '&:hover': {
      backgroundColor: palette.surface01dp[palette.type],
    },
    marginRight: 0,
    width: '100%',
  },
  searchIcon: {
    alignItems: 'center',
    display: 'flex',
    height: '100%',
    justifyContent: 'center',
    left: '12px',
    margin: '0',
    pointerEvents: 'none',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '18px',
    '& path': {
      fill: palette.grey2[palette.type],
    },
  },
  inputRoot: {
    color: `5px solid ${palette.secondaryLabel[palette.type]}`,
    fontSize: '14px',
    fontWeight: 'normal',
    lineHeight: '1.43',
    width: '100%',
  },
  inputInput: {
    boxSizing: 'border-box',
    height: '44px',
    padding: '12px 12px 12px 40px',
    width: '100%',
  },
}))
