// flow-typed signature: 4cdf2713ff71e463478d370538858891
// flow-typed version: <<STUB>>/@walletconnect/web3-provider_v^1.0.0-beta.37/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@walletconnect/web3-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@walletconnect/web3-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@walletconnect/web3-provider/lib' {
  declare module.exports: any;
}

declare module '@walletconnect/web3-provider/src/http' {
  declare module.exports: any;
}

declare module '@walletconnect/web3-provider/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@walletconnect/web3-provider/lib/index' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/lib'>;
}
declare module '@walletconnect/web3-provider/lib/index.js' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/lib'>;
}
declare module '@walletconnect/web3-provider/src/http.js' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/src/http'>;
}
declare module '@walletconnect/web3-provider/src/index' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/src'>;
}
declare module '@walletconnect/web3-provider/src/index.js' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/src'>;
}
