// @flow

export type NotifiedTransaction = {
  CONNECT_WALLET_TX: string,
  STANDARD_TX: string,
  CONFIRMATION_TX: string,
  OWNER_CHANGE_TX: string,
  SAFE_NAME_CHANGE_TX: string,
  OWNER_NAME_CHANGE_TX: string,
  THRESHOLD_CHANGE_TX: string,
  NETWORK_TX: string,
}

export const NOTIFIED_TRANSACTIONS: NotifiedTransaction = {
  CONNECT_WALLET_TX: 'CONNECT_WALLET_TX',
  STANDARD_TX: 'STANDARD_TX',
  CONFIRMATION_TX: 'CONFIRMATION_TX',
  OWNER_CHANGE_TX: 'OWNER_CHANGE_TX',
  SAFE_NAME_CHANGE_TX: 'SAFE_NAME_CHANGE_TX',
  OWNER_NAME_CHANGE_TX: 'OWNER_NAME_CHANGE_TX',
  THRESHOLD_CHANGE_TX: 'THRESHOLD_CHANGE_TX',
  NETWORK_TX: 'NETWORK_TX',
}
