// flow-typed signature: ee010e9c75b42bfb961c1c5c4ee4160f
// flow-typed version: <<STUB>>/@toruslabs/torus-embed_v0.2.6/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@toruslabs/torus-embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@toruslabs/torus-embed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@toruslabs/torus-embed/dist/config' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/createErrorMiddleware' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/createTransformEthAddressMiddleware' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/embed' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/embedUtils' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/inpage-provider' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/stream-utils' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/utils/httpHelpers' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/public' {
  declare module.exports: any;
}

// Filename aliases
declare module '@toruslabs/torus-embed/dist/config.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/config'>;
}
declare module '@toruslabs/torus-embed/dist/createErrorMiddleware.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/createErrorMiddleware'>;
}
declare module '@toruslabs/torus-embed/dist/createTransformEthAddressMiddleware.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/createTransformEthAddressMiddleware'>;
}
declare module '@toruslabs/torus-embed/dist/embed.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/embed'>;
}
declare module '@toruslabs/torus-embed/dist/embedUtils.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/embedUtils'>;
}
declare module '@toruslabs/torus-embed/dist/inpage-provider.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/inpage-provider'>;
}
declare module '@toruslabs/torus-embed/dist/stream-utils.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/stream-utils'>;
}
declare module '@toruslabs/torus-embed/dist/utils/httpHelpers.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/utils/httpHelpers'>;
}
declare module '@toruslabs/torus-embed/index' {
  declare module.exports: $Exports<'@toruslabs/torus-embed'>;
}
declare module '@toruslabs/torus-embed/index.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed'>;
}
declare module '@toruslabs/torus-embed/public/index' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/public'>;
}
declare module '@toruslabs/torus-embed/public/index.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/public'>;
}
