/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IChocoInitializableInterface extends ethers.utils.Interface {
  functions: {
    "initialize(string,string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class IChocoInitializable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IChocoInitializableInterface;

  functions: {
    initialize(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(string,string,address)"(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  initialize(
    _name: string,
    _symbol: string,
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(string,string,address)"(
    _name: string,
    _symbol: string,
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(string,string,address)"(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    initialize(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(string,string,address)"(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(string,string,address)"(
      _name: string,
      _symbol: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
