// flow-typed signature: f6f4916ab4d700d3db6ac07b4264aa7e
// flow-typed version: <<STUB>>/@storybook/addon-links_v5.2.6/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-links/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/react/components/link' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/react/components/RoutedLink' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-links/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/constants'>;
}
declare module '@storybook/addon-links/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist'>;
}
declare module '@storybook/addon-links/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist'>;
}
declare module '@storybook/addon-links/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/manager'>;
}
declare module '@storybook/addon-links/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/preview'>;
}
declare module '@storybook/addon-links/dist/react/components/link.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react/components/link'>;
}
declare module '@storybook/addon-links/dist/react/components/RoutedLink.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react/components/RoutedLink'>;
}
declare module '@storybook/addon-links/dist/react/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react'>;
}
declare module '@storybook/addon-links/dist/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react'>;
}
declare module '@storybook/addon-links/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/typings.d'>;
}
declare module '@storybook/addon-links/react.js' {
  declare module.exports: $Exports<'@storybook/addon-links/react'>;
}
declare module '@storybook/addon-links/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/register'>;
}
