// flow-typed signature: c905b8c93e093290a3c272e675bae6a2
// flow-typed version: <<STUB>>/@storybook/addon-knobs_v^3.3.15/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-knobs/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/angular/helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/angular/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/angular/utils' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/base' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/PropField' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Date/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Date/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/react/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/react/WrapStory' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/vue/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/example/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/angular/helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/angular/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/angular/utils' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/base' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/__tests__/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/__tests__/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/PropField' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Date/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Date/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/KnobManager.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/react/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/react/index.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/react/WrapStory' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/vue/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/vue/index.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-knobs/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/angular'>;
}
declare module '@storybook/addon-knobs/dist/angular/helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/angular/helpers'>;
}
declare module '@storybook/addon-knobs/dist/angular/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/angular/index'>;
}
declare module '@storybook/addon-knobs/dist/angular/utils.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/angular/utils'>;
}
declare module '@storybook/addon-knobs/dist/base.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/base'>;
}
declare module '@storybook/addon-knobs/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/Panel'>;
}
declare module '@storybook/addon-knobs/dist/components/PropField.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/PropField'>;
}
declare module '@storybook/addon-knobs/dist/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/PropForm'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Array'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Button'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Color'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Date/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Date/index'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Date/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Date/styles'>;
}
declare module '@storybook/addon-knobs/dist/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/index'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Number'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Object'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Select'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Text'>;
}
declare module '@storybook/addon-knobs/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/index'>;
}
declare module '@storybook/addon-knobs/dist/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobManager'>;
}
declare module '@storybook/addon-knobs/dist/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobStore'>;
}
declare module '@storybook/addon-knobs/dist/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/react/index'>;
}
declare module '@storybook/addon-knobs/dist/react/WrapStory.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/react/WrapStory'>;
}
declare module '@storybook/addon-knobs/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/register'>;
}
declare module '@storybook/addon-knobs/dist/vue/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/vue/index'>;
}
declare module '@storybook/addon-knobs/example/stories/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/example/stories/index'>;
}
declare module '@storybook/addon-knobs/react.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/react'>;
}
declare module '@storybook/addon-knobs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/register'>;
}
declare module '@storybook/addon-knobs/src/angular/helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/angular/helpers'>;
}
declare module '@storybook/addon-knobs/src/angular/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/angular/index'>;
}
declare module '@storybook/addon-knobs/src/angular/utils.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/angular/utils'>;
}
declare module '@storybook/addon-knobs/src/base.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/base'>;
}
declare module '@storybook/addon-knobs/src/components/__tests__/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/__tests__/Array'>;
}
declare module '@storybook/addon-knobs/src/components/__tests__/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/__tests__/Panel'>;
}
declare module '@storybook/addon-knobs/src/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/Panel'>;
}
declare module '@storybook/addon-knobs/src/components/PropField.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/PropField'>;
}
declare module '@storybook/addon-knobs/src/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/PropForm'>;
}
declare module '@storybook/addon-knobs/src/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Array'>;
}
declare module '@storybook/addon-knobs/src/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/src/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Button'>;
}
declare module '@storybook/addon-knobs/src/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Color'>;
}
declare module '@storybook/addon-knobs/src/components/types/Date/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Date/index'>;
}
declare module '@storybook/addon-knobs/src/components/types/Date/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Date/styles'>;
}
declare module '@storybook/addon-knobs/src/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/index'>;
}
declare module '@storybook/addon-knobs/src/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Number'>;
}
declare module '@storybook/addon-knobs/src/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Object'>;
}
declare module '@storybook/addon-knobs/src/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Select'>;
}
declare module '@storybook/addon-knobs/src/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Text'>;
}
declare module '@storybook/addon-knobs/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/index'>;
}
declare module '@storybook/addon-knobs/src/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/KnobManager'>;
}
declare module '@storybook/addon-knobs/src/KnobManager.test.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/KnobManager.test'>;
}
declare module '@storybook/addon-knobs/src/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/KnobStore'>;
}
declare module '@storybook/addon-knobs/src/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/react/index'>;
}
declare module '@storybook/addon-knobs/src/react/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/react/index.test'>;
}
declare module '@storybook/addon-knobs/src/react/WrapStory.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/react/WrapStory'>;
}
declare module '@storybook/addon-knobs/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/register'>;
}
declare module '@storybook/addon-knobs/src/vue/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/vue/index'>;
}
declare module '@storybook/addon-knobs/src/vue/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/vue/index.test'>;
}
declare module '@storybook/addon-knobs/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/vue'>;
}
