name: Run e2e
# Run on pushes to dev/main or PR
on:
  # Pull request hook without any config. Launches for every pull request
  pull_request:
  # Launches for pushes to main or dev
  push:

jobs:
  e2e:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.E2E_RUN_HOOK_ACCESS_TOKEN }}
          repository: gnosis/safe-react-e2e-tests
          event-type: run-e2e-from-safe-react