name: Mint PR NFT

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'PR number'
        required: true

jobs:
  mint:
    environment: Manual
    name: Mint
    runs-on: ubuntu-latest
    steps:
      - name: Mint
        uses: web3actions/tx@d3833db41e58cb4e7f329027ad30211a22e1c5e5
        with:
          rpc-node: ${{ secrets.RPC_NODE}}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: ${{ secrets.CONTRACT_ADDRESS }}
          function: "mint(address _to, uint256 _tokenId, string _uri)"
          inputs: '[ "${{ secrets.WALLET_ADDRESS }}", ${{ github.event.inputs.prNumber }}, "https://github.com/gnosis/safe-react/pull/${{ github.event.inputs.prNumber }}" ]'
          value: "0"

      - name: Set success comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.inputs.prNumber }}
          body: |
            [<img alt="GitMint NFT preview" width="200" src="https://gitsvg.katspaugh.workers.dev/?svg=1&url=https://github.com/gnosis/safe-react/pull/${{ github.event.inputs.prNumber }}" />](https://blockscout.com/xdai/mainnet/token/${{ secrets.CONTRACT_ADDRESS }}/instance/${{ github.event.inputs.prNumber }})

            Thank you for your contribution! Please, let us know your Ethereum address to receive [this NFT on Gnosis Chain](https://epor.io/tokens/${{ secrets.CONTRACT_ADDRESS }}/${{ github.event.inputs.prNumber }}?network=xDai).
            Cheers! 🏆
