name: Mint PR NFT

on:
  pull_request:
    branches:
      - dev

jobs:
  mint:
    environment: Manual
    name: Mint
    runs-on: ubuntu-latest
    steps:
      - name: Check if already minted
        uses: web3actions/tx@d3833db41e58cb4e7f329027ad30211a22e1c5e5
        with:
          rpc-node: ${{ secrets.RPC_NODE}}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: ${{ secrets.CONTRACT_ADDRESS }}
          function: "tokenURI(uint256 _tokenId)"
          inputs: '[ ${{ github.event.number }} ]'
          value: "0"

      - name: Mint
        id: mint
        if: ${{ failure() }}
        uses: web3actions/tx@d3833db41e58cb4e7f329027ad30211a22e1c5e5
        with:
          rpc-node: ${{ secrets.RPC_NODE}}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: ${{ secrets.CONTRACT_ADDRESS }}
          function: "mint(address _to, uint256 _tokenId, string _uri)"
          inputs: '[ "${{ secrets.WALLET_ADDRESS }}", ${{ github.event.number }}, "https://github.com/gnosis/safe-react/pull/${{ github.event.number }}" ]'
          value: "0"

      - name: Set success comment
        if: steps.mint.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            [<img alt="GitMint NFT preview" width="200" src="https://gitsvg.katspaugh.workers.dev/?svg=1&url=https://github.com/gnosis/safe-react/pull/${{ github.event.number }}" />](https://blockscout.com/xdai/mainnet/token/${{ secrets.CONTRACT_ADDRESS }}/instance/${{ github.event.number }})

            Dear @${{ github.event.pull_request.user.login }},
            Thank you for your contribution! Please, let us know your Ethereum address to receive [this NFT on Gnosis Chain](https://epor.io/tokens/${{ secrets.CONTRACT_ADDRESS }}/${{ github.event.number }}?network=xDai).
            Cheers! 🏆
